/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Game;
import Classes.Referee;
import Classes.Team;
import javax.swing.JOptionPane;

/**
 *
 * @author blao
 */
public class UpdateGameSetForm extends javax.swing.JFrame {
    int currentGameSet;
    /**
     * Creates new form UpdateGameForm
     */
    public UpdateGameSetForm(int gameSet) {
        initComponents();
        cmbTeamPopulate();
        loadReferees();
        currentGameSet = gameSet;
        loadGameSet(currentGameSet);

    }
    
    public UpdateGameSetForm() {
        initComponents();
        cmbTeamPopulate();
        loadReferees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbReferee2 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtDate2 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbHomeTeam1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cmbAwayTeam1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spnHomeGoals1 = new javax.swing.JSpinner();
        cmbReferee1 = new javax.swing.JComboBox<>();
        spnAwayGoals1 = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbHomeTeam2 = new javax.swing.JComboBox<>();
        cmbAwayTeam2 = new javax.swing.JComboBox<>();
        spnHomeGoals2 = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        buttonUpdate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDate1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnAwayGoals2 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Game");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Goals");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Home");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Away");

        jLabel16.setText("Referee:");

        cmbReferee2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel17.setText("Game Date:");

        txtDate2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txtDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Home Team");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("-");

        cmbHomeTeam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbHomeTeam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHomeTeam1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Goals");

        cmbAwayTeam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbAwayTeam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAwayTeam1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Home");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Away");

        jLabel10.setText("Referee:");

        cmbReferee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel23.setText("Update Game 1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Away Team");

        cmbHomeTeam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbHomeTeam2.setEnabled(false);

        cmbAwayTeam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbAwayTeam2.setEnabled(false);

        buttonUpdate.setText("Update Game Set");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Update Game 2");

        jLabel7.setText("Game Date:");

        txtDate1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txtDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Home Team");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Away Team");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("-");

        buttonDelete.setText("Delete Game Set");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(buttonUpdate)
                .addGap(42, 42, 42)
                .addComponent(buttonDelete)
                .addGap(110, 110, 110))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGap(90, 90, 90))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(cmbHomeTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAwayTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addGap(90, 90, 90))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(cmbHomeTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAwayTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(spnHomeGoals2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jLabel12))
                                                        .addComponent(jLabel14))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(spnAwayGoals2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(cmbReferee2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(29, 29, 29)
                                                    .addComponent(jLabel13))))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(spnHomeGoals1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jLabel19))
                                                        .addComponent(jLabel21))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel22)
                                                        .addComponent(spnAwayGoals1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(29, 29, 29)
                                                    .addComponent(jLabel20))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cmbReferee1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel23))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2))
                            .addGap(20, 20, 20)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(buttonUpdate))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel23)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbHomeTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbAwayTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spnHomeGoals1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(spnAwayGoals1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(cmbReferee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbHomeTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbAwayTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spnHomeGoals2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(spnAwayGoals2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(cmbReferee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate2ActionPerformed

    private void cmbHomeTeam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHomeTeam1ActionPerformed
        // TODO add your handling code here:
        String teamBox = "HOME";
        this.cmbTeamSelect(teamBox);
    }//GEN-LAST:event_cmbHomeTeam1ActionPerformed

    private void cmbAwayTeam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAwayTeam1ActionPerformed
        // TODO add your handling code here:
        String teamBox = "AWAY";
        this.cmbTeamSelect(teamBox);
    }//GEN-LAST:event_cmbAwayTeam1ActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        int gameSet;
        int homeIndex;
        int awayIndex;
        int homeID;
        int awayID;

        int homeGoals;
        int awayGoals;

        int refereeIndex;
        int refereeID;

        String date;

        Team t = new Team("jflDB");
        Object[][] teamRecords = t.loadAllTeams();
        t.closeConnection();

        //Add 1st Game of Game set

        homeIndex = cmbHomeTeam1.getSelectedIndex();
        if(homeIndex > 0){
            homeIndex = homeIndex - 1;
            homeID = Integer.parseInt(teamRecords[homeIndex][0].toString());
        }else{
            homeID = 0;
        }

        awayIndex = cmbAwayTeam1.getSelectedIndex();
        if(awayIndex > 0){
            awayIndex = awayIndex - 1;
            awayID = Integer.parseInt(teamRecords[awayIndex][0].toString());
        }else{
            awayID = 0;
        }

        homeGoals = (Integer) spnHomeGoals1.getValue();
        awayGoals = (Integer) spnAwayGoals1.getValue();

        Referee r = new Referee("jflDB");
        Object[][] refereeRecords = r.loadAllReferees();
        r.closeConnection();

        refereeIndex = cmbReferee1.getSelectedIndex();
        if(refereeIndex > 0){
            refereeIndex = refereeIndex - 1;
            refereeID = Integer.parseInt(refereeRecords[refereeIndex][1].toString());
        }else{
            refereeID = 0;
        }

        date = txtDate1.getText();

        Game g = new Game("jflDB");
        g.updateRecord(currentGameSet,1,homeID,awayID,homeGoals,awayGoals,refereeID,date);
       

        //Add 2nd Game of Game set

        homeIndex = cmbHomeTeam2.getSelectedIndex();
        if(homeIndex > 0){
            homeIndex = homeIndex - 1;
            homeID = Integer.parseInt(teamRecords[homeIndex][0].toString());
        }else{
            homeID = 0;
        }

        awayIndex = cmbAwayTeam2.getSelectedIndex();
        if(awayIndex > 0){
            awayIndex = awayIndex - 1;
            awayID = Integer.parseInt(teamRecords[awayIndex][0].toString());
        }else{
            awayID = 0;
        }

        homeGoals = (Integer) spnHomeGoals2.getValue();
        awayGoals = (Integer) spnAwayGoals2.getValue();

        refereeIndex = cmbReferee2.getSelectedIndex();
        if(refereeIndex > 0){
            refereeIndex = refereeIndex - 1;
            refereeID = Integer.parseInt(refereeRecords[refereeIndex][1].toString());
        }else{
            refereeID = 0;
        }

        date = txtDate2.getText();

        g.updateRecord(currentGameSet,2,homeID,awayID,homeGoals,awayGoals,refereeID,date);

        g.closeConnection();

        JOptionPane.showMessageDialog(this, "Game successfully updated.");

    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void txtDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate1ActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        int confirmDelete = JOptionPane.showConfirmDialog(this, "Do you want to delete this game record?", "Delete Record", JOptionPane.YES_NO_OPTION);
        if (confirmDelete == 0) {
            System.out.println("Confirmed");
            Game g = new Game("jflDB");
            g.deleteRecord(currentGameSet);
            g.closeConnection();
        
            JOptionPane.showMessageDialog(this, "Record Deleted!");
            this.dispose();
        }else{
            System.out.println("Not Confirmed");
            
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateGameSetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateGameSetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateGameSetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateGameSetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateGameSetForm().setVisible(true);
            }
        });
    }
    
    private void cmbTeamPopulate(){
        Team t = new Team("jflDB");
        String[] teams = t.populateTeamComboBox();
        
       for( int i=0; i<teams.length ; i++){
           cmbHomeTeam1.addItem(teams[i]);
           cmbHomeTeam2.addItem(teams[i]);
           cmbAwayTeam1.addItem(teams[i]);
           cmbAwayTeam2.addItem(teams[i]);
        }
 
        t.closeConnection(); 
    }
    
    private void loadReferees(){
        Referee r = new Referee("jflDB");
        Object[][] refereeRecords = r.loadAllReferees();
        String firstName;
        String lastName;
        
       for( int i=0; i<refereeRecords.length ; i++){
           firstName = refereeRecords[i][2].toString();
           lastName = refereeRecords[i][3].toString();
           cmbReferee1.addItem(firstName+" "+lastName);
           cmbReferee2.addItem(firstName+" "+lastName);
        }
 
        r.closeConnection(); 
        
    }
    
    private void cmbTeamSelect(String teamBox){
        int selectedIndex;
        int otherIndex;
        
        if (teamBox == "HOME"){
            selectedIndex = cmbHomeTeam1.getSelectedIndex();
            otherIndex = cmbAwayTeam1.getSelectedIndex();
            
            if (selectedIndex == otherIndex){
                cmbAwayTeam1.setSelectedIndex(0);
            }
            
            cmbAwayTeam2.setSelectedIndex(selectedIndex);
        }else if(teamBox == "AWAY"){
            selectedIndex = cmbAwayTeam1.getSelectedIndex();
            otherIndex = cmbHomeTeam1.getSelectedIndex();
            
            if (selectedIndex == otherIndex){
                cmbHomeTeam1.setSelectedIndex(0);
            }
            
            cmbHomeTeam2.setSelectedIndex(selectedIndex);
            
        }
          
    }
    
    private void loadGameSet(int gameSet){
        Game g = new Game("jflDB");
        Object[][] gameSetRecord = g.loadDetails(gameSet);
        g.closeConnection();
        
        Team t = new Team("jflDB");
        String homeTeam = t.getTeamName(Integer.parseInt(gameSetRecord[0][2].toString()));
        String awayTeam = t.getTeamName(Integer.parseInt(gameSetRecord[1][2].toString()));
        t.closeConnection();
        
        cmbHomeTeam1.setSelectedItem(homeTeam);
        cmbAwayTeam1.setSelectedItem(awayTeam);
        
        spnHomeGoals1.setValue(Integer.parseInt(gameSetRecord[0][4].toString()));
        spnAwayGoals1.setValue(Integer.parseInt(gameSetRecord[0][5].toString()));
        
        spnHomeGoals2.setValue(Integer.parseInt(gameSetRecord[1][4].toString()));
        spnAwayGoals2.setValue(Integer.parseInt(gameSetRecord[1][5].toString()));
        
        txtDate1.setText(gameSetRecord[0][7].toString());
        txtDate2.setText(gameSetRecord[1][7].toString());
        
        Referee r = new Referee("jflDB");
        Object[] refereeRecord = r.loadDetails(Integer.parseInt(gameSetRecord[0][6].toString()));
        String firstName = refereeRecord[1].toString();
        String lastName = refereeRecord[2].toString();
        String fullName = firstName+" "+lastName;
        
        cmbReferee1.setSelectedItem(fullName);
        
        refereeRecord = r.loadDetails(Integer.parseInt(gameSetRecord[1][6].toString()));
        firstName = refereeRecord[1].toString();
        lastName = refereeRecord[2].toString();
        fullName = firstName+" "+lastName;
        
        cmbReferee2.setSelectedItem(fullName);
        
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> cmbAwayTeam1;
    private javax.swing.JComboBox<String> cmbAwayTeam2;
    private javax.swing.JComboBox<String> cmbHomeTeam1;
    private javax.swing.JComboBox<String> cmbHomeTeam2;
    private javax.swing.JComboBox<String> cmbReferee1;
    private javax.swing.JComboBox<String> cmbReferee2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner spnAwayGoals1;
    private javax.swing.JSpinner spnAwayGoals2;
    private javax.swing.JSpinner spnHomeGoals1;
    private javax.swing.JSpinner spnHomeGoals2;
    private javax.swing.JFormattedTextField txtDate1;
    private javax.swing.JFormattedTextField txtDate2;
    // End of variables declaration//GEN-END:variables
}
